// #include'ing this file sets up needed analysis functions

#include "../BToDKTo3piK/analysis/getParams.cc"
#include "../BToDKTo3piK/analysis/numEvtsMC.cc"
#include "../BToDKTo3piK/analysis/getCorr.cc"
#include "../BToDKTo3piK/analysis/getRanPar.cc"
#include "../BToDKTo3piK/analysis/getRanCorr.cc"
#include "../BToDKTo3piK/analysis/fitFullMcNoCorr.cc"
#include "../BToDKTo3piK/analysis/fitFullMc.cc"
#include "../BToDKTo3piK/analysis/BBqqSideband.cc"
#include "../BToDKTo3piK/analysis/CheckMcCorr.cc"
#include "../BToDKTo3piK/analysis/fitChunks.cc"
#include "../BToDKTo3piK/analysis/fitChunks2.cc"
#include "../BToDKTo3piK/analysis/fitManyChunksSig.cc"
#include "../BToDKTo3piK/analysis/fitManyChunksSig2.cc"
#include "../BToDKTo3piK/analysis/fitManyChunks.cc"
#include "../BToDKTo3piK/analysis/fitProgChunks.cc"
#include "../BToDKTo3piK/analysis/fitOnVariables.cc"
#include "../BToDKTo3piK/analysis/newChunks.cc"
#include "../BToDKTo3piK/analysis/fitShapedFlat.cc"
#include "../BToDKTo3piK/analysis/plotComponents.cc"
